name: 'Build'
run-name: 'ğŸ‹ Build | ${{ github.event.head_commit.message || github.event.pull_request.title }}'
on:
  push:
    branches:
      - master

jobs:
  build:
    name: ğŸ‹
    uses: ./.github/workflows/_build.yml
    with:
      meteor_version: ${{ matrix.meteor_version }}
      docker_push: false
    strategy:
      matrix:
        meteor_version:
          - 3.0
          - 3.1.1