name: 'Publish'
run-name: 'ğŸ‹ Publish | ${{ github.event.head_commit.message || github.event.pull_request.title }}'
on:
  push:
    branches:
      - master

jobs:
  build:
    uses: .github/workflows/_build.yml
    with:
      meteor_version: ${{ matrix.meteor_version }}
    strategy:
      matrix:
        meteor_version:
          - 3.0.0
          - 3.1.1